### ISSUE TITLE
Het is beter om alle input types 400 pixels te maken

### ISSUE THREAD

**Issue by JeroenHeemskerk** [MilanLucas/educom-webshop-basis-1707216396#18]
In de code hieronder zet je alleen voor de `<input type="text">` de breedte op 400px https://github.com/MilanLucas/educom-webshop-basis-1707216396/blob/f87eb547be6b0f2761d43f372a2249e011381a5e/mystyle.css#L33-L35

Als we straks andere typen gaan gebruiken (zoals `<input type="email">`, `<input type="password">`) dan zullen deze niet 400px zijn.

beter is het om alle input tags 400px te maken en dan voor bijv. types radio en submit dit ongedaan te maken.
```css
 p.persoon input, select, textarea { 
 	width: 400px; 
 }
 input[type=radio], input[type=submit] {
 	width: auto; 
 }  
```
